version: "3.8"

services:
    api-service:
        image: api-service
        build:
            context: ./api-service
            dockerfile: Dockerfile.dev
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
        ports:
            - '8080:8080'
        restart: always

    eureka-server:
        image: eureka-server
        build:
            context: ./eureka-server/
            dockerfile: Dockerfile.dev
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
        tty: false
        ports:
            - "8761:8761"
        restart: always
    
    zuul-server:
        image: zuul-server
        build:
            context: ./zuul-server/
            dockerfile: Dockerfile.dev
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
        tty: false
        ports:
            - "8762:8762"
        restart: always

    keycloak:
        image: keycloak
        build:
            context: ./keycloak/
            dockerfile: Dockerfile.dev
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
            
        tty: false
        ports:
            - "8180:8180"
        restart: always
            